//======================= Screen Names ===================//
const SCREENS = {
    MAIN: 'main',
    TABS: 'tabs',
    HOROSCOPE: 'Horoscope',
    SPLASH: 'splash',
    LOGIN: 'login',
    FORGET_PASSWORD: 'forgetPassword',
    RESET_PASSWORD: 'reset password',
    REGISTER: 'register',
    PRIVACY_POLICY: 'privacypolicy',
    DASHBOARD: 'dashboard',
    OTP:'otp',
    CREATE_PASSWORD:'createPassword',
    ONE_LAST:'onelast',
    ASTROLOGY:'AstrologySelection',
    TRANSIT:'Transit',
    CALENDER:'Calender',
    SUBSCRIPTION:'subscription',
    KEYPOINT:'keypoint',
    TRANSITINFORMATION:"transitinformation",
    RETROGRADE:"retrograde",
    RETROGRADE_PLANET:"retrogradeplanetdetails",
    REMEDIES:"remedies",
    FULLMOON:"fullmoon",
    PLANET_PLACEMENT:"planetplacement",
    HOUSE_PLACEMENT:"houseplacement",
    LUNAR_CALENDER:"lunarcalender",
    FAQ:"Faq",
    MY_PROFILE:"myprofile",
    CONTACT:"contact",
    PAYMENT:"payment",
};

//==================== Validation Messages =================//
const VALIDATE_FORM = {
    FIRST_NAME: 'Please enter first name.',
    LAST_NAME: 'Please enter last name.',
    EMAIL: 'Please enter email address.',
    EMAIL_VALID: 'Please enter valid email address.',
    PASSWORD: 'Please enter password.',
    BIRTH_DATE:'please enter your birth date',
    BIRTH_TIME:'Please enter your birth time',
    VALID_PASSWORD: 'Please enter valid password eg. Arsy@898',
    VALID_PHONE: 'Please enter valid mobile number.',
    DOB: 'Please enter DOB.',
    BIRTH_PLACE:'Please enter your birth place',
    OTP:'Please enter OTP number',
    SCREEN_NAME: 'Please enter screen name',
    C_PASSWORD: 'Please enter confirm password.',
    MISMATCH: "Password doesn't match",
    LOGOUT: 'Are you sure you want to logout?',
    PRIVACY: 'Please select post privacy.',
    ADDRESS: 'Please enter location',
    GENDER: 'Please select gender.',
    TERMS_AND_CODITION: 'Please Accept Terms & Conditions and Privacy Policy.',
};

export {
    SCREENS,
    VALIDATE_FORM,
};