export const ActionType = {
    //======= For User Login ========
    USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGIN: 'USER_LOGIN',

    //======= For User Registration ========
    USER_REGISTER_LOADING: 'USER_REGISTER_LOADING',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER: 'USER_REGISTER'
};