//================= Images files add here =============//
const Images = {
    splash: require('./Splash/splash.png'),
    // menu: require('./menu/menu.png'),
    // notification: require('./notification/notification.png'),
    back2:require('./back/back.png'),
    dummy: require('./user/dummy.png'),
    home1: require('./menu/home1.png'),
    // logout: require('./menu/logout.png'),
    setting: require('./menu/setting.png'),
    user: require('./menu/user.png'),
    user1: require('./login/user1.png'),
    email: require('./login/email.png'),
    lock: require('./login/lock.png'),
    facebook: require('./login/facebook.png'),
    google: require('./login/google.png'),
    home: require('./tab/home.png'),
    forgot: require('./login/forgot.png'),
    clock: require('./tab/clock.png'),
    location2:require('./calender/location1.png'),
    backscreen: require('./login/backscreen.png'),
    chakra: require('./login/chakra.png'),
    register: require('./registration/register.png'),
    checkbox: require('./registration/checkbox.png'),
    timer: require('./resetpassword/timer.png'),
    back: require('./onelastthing/back.png'),
    name: require('./onelastthing/name.png'),
    birth: require('./onelastthing/birthdate.png'),
    birthtime: require('./onelastthing/birthtime.png'),
    location: require('./onelastthing/location.png'),
    gender: require('./onelastthing/gender.png'),
    cross: require('./login/cross.png'),
    half: require('./onelastthing/half.png'),
    menu: require('./drawer/menu.png'),
    cross1: require('./login/cross1.png'),
    notification: require('./drawer/notification.png'),
    profileuser: require('./drawer/profileuser.png'),
    home2: require('./drawer/home.png'),
    horoscope: require('./drawer/horoscope.png'),
    transit: require('./drawer/transit.png'),
    calender: require('./drawer/calender.png'),
    subscription: require('./drawer/subscription.png'),
    retro: require('./retroradeplanet/retro.png'),
    arrow: require('./drawer/arrow.png'),
    logout: require('./drawer/logout.png'),
    cross2: require('./login/cross2.png'),
    birthchart:require('./horizontal/birthchart.png'),
    ascedant:require('./horizontal/ascedants.png'),
    planet:require('./horizontal/planet.png'),
    keypoint:require('./horizontal/keypoint.png'),
   CHAKR:require('./horizontal/chkr.png'),
   SYMBOL:require('./horizontal/symbol.png'),
   camera2:require('./myprofile/camera1.png'),
   SOUTH:require('./horizontal/southnode.png'),
  NORTH:require('./horizontal/northnode.png'),
  CHIRON:require('./horizontal/chiron.png'),
  SUN:require('./horizontal/sun.png'),
  NEPTUNE:require('./horizontal/neptune.png'),
  PLUTO:require('./horizontal/pluto.png'),
  SATURN:require('./horizontal/saturn.png'),
  BLACKMOON:require('./horizontal/blackmoon.png'),
  MOON:require('./horizontal/moon.png'),
  VENUS:require('./horizontal/venus.png'),
  MERCURY:require('./horizontal/mercury.png'),
  EARTH:require('./horizontal/earth.png'),
  WHITEMOON:require('./horizontal/whitemoon.png'),
  URANUS:require('./horizontal/uranus.png'),
  MARS:require('./horizontal/mars.png'),
  JUPITOR:require('./horizontal/jupitor.png'),
  PROSERPINE:require('./horizontal/proserpine.png'),
  LIBRA:require('./horizontal/libra1.png'),
  VIRGO:require('./horizontal/virgo2.png'),
  MER:require('./horizontal/mercury2.png'),
 SUNEMOJ:require('./horizontal/sunemoj.png'),
 MOONEMOJ:require('./horizontal/moonemoj.png'),
 CIRCLE:require('./horizontal/circle.png'),
 TRANSIT:require('./transits/transit.png'),
 MOONINFORM:require('./transits/mooninformation.png'),
 PLANETINFORM:require('./transits/planet1.png'),
 HOUSE:require('./transits/house1.png'),
 ARROW:require('./transits/arrow.png'),
 moon2:require('./transitinformation/moon2.png'),
fulmoon:require('./transitinformation/fulmoon.png'),
halfmoon:require('./transitinformation/moon3.png'),
halfsun:require('./transitinformation/sun2.png'),
notomoon:require('./retroradeplanet/notomoon.png'),
backpress:require('./transitinformation/backpress.png'),
forward:require('./transitinformation/forward.png'),
personalhoro:require('./horoscope/personalhoro.png'),
aquarius:require('./horoscope/Aquarius.png'),
prisces:require('./horoscope/prisces.png'),
aries:require('./horoscope/aries.png'),
taurus:require('./horoscope/taurus.png'),
gemini:require('./horoscope/gemini.png'),
cancer:require('./horoscope/cancer.png'),
leo:require('./horoscope/leo.png'),
virgo4:require('./horoscope/virgo4.png'),
libra2:require('./horoscope/libra2.png'),
scorpio:require('./horoscope/scorpio.png'),
sagitarius:require('./horoscope/sagitarius.png'),
capricorn:require('./horoscope/capricorn.png'),
lunarcalender:require('./mooncalendar/lunar.png'),
mon1:require('./mooncalendar/mon1.png'),
calender1:require('./transits/calender1.png'),
time1:require('./transits/time1.png'),
add:require('./calender/plus.png'),
camera:require('./myprofile/profile.png'),
downArrow:require('./contactus/down.png'),
BookOne:require('./contactus/bookone.png'),
home3:require('./calender/home4.png'),
retro3:require('./birthchart/retro3.png'),
minus:require('./calender/mine.png'),
moon1:require('./calender/moon1.png'),
moon3:require('./calender/moon2.png'),
moon4:require('./calender/moon2.png'),
moon5:require('./calender/moon4.png'),
moon6:require('./calender/moon5.png'),
moon7:require('./calender/moon6.png'),
moon8:require('./calender/moon7.png'),
moon9:require('./calender/moon8.png'),
moon10:require('./calender/moon9.png'),
location3:require('./calender/location2.png'),
download:require('./calender/download.png'),
moon11:require('./calender/moon10.png'),
moon12:require('./calender/moon11.png'),
male:require('./calender/male.png'),
girl:require('./calender/girl.png'),
unit:require('./calender/unit1.png'),
moon13:require('./calender/moon12.png'),
BackArrow:require('./calender/backarrow.png'),
faCcPaypal:require('./calender/Paypal.png'),
// Mastercard:require('./calender/Matercard.png'),
Mastercard1:require('./calender/Mastercard.png'),
cibCcVisa:require('./calender/Visa.png'),
twemojiCreditCard:require('./calender/CreditCard.png'),
up:require('./calender/up.png'),
jupiter:require('./calender/jupiter.png'),
down:require('./calender/down.png'),
moon14:require('./calender/moon13.png'),
moon15:require('./calender/moon14.png'),
moon16:require('./calender/moon15.png'),
moon17:require('./calender/moon16.png'),
moon18:require('./calender/moon17.png'),
moon19:require('./calender/moon18.png'),
moon20:require('./calender/moon19.png'),
moon21:require('./calender/moon20.png'),
moon22:require('./calender/moon21.png'),
moon23:require('./calender/moon22.png'),
moon24:require('./calender/moon23.png'),
moon25:require('./calender/moon24.png'),
moon26:require('./calender/moon25.png'),
moon27:require('./calender/moon25.png'),
moon28:require('./calender/moon28.png'),
moon29:require('./calender/moon29.png'),
moon30:require('./calender/moon30.png'),
chironcal:require('./calender/chironcal.png'),
suncal:require('./calender/suncal.png'),
neptunecal:require('./calender/neptunecal.png'),
plutocal:require('./calender/plutocal.png'),
saturncal:require('./calender/saturncal.png'),
blackmooncal:require('./calender/blackmooncal.png'),
mooncal:require('./calender/mooncal.png'),
fourthcurcle:require('./calender/fourthcircle.png'),
venuscal:require('./calender/venuscal.png'),
mercurycal:require('./calender/mercurycal.png'),
earthcal:require('./calender/earthcal.png'),
firstcircle:require('./calender/firstimage.png'),
secondcircle:require('./calender/secondimage.png'),
thirdcircle:require('./calender/thirdcircle.png'),
whitemooncal:require('./calender/whitemooncal.png'),
uranuscal:require('./calender/uranuscal.png'),
marscal:require('./calender/marscal.png'),
jupitercal:require('./calender/jupitercal.png'),
proscal:require('./calender/proscal.png'),
world:require('./myprofile/world.png')
// upArrow:require('../Assets/cont/upArrow.png'),
// location1:require('./transits/location1.png'),

};
export { Images };